In [1]:
import numpy as np

In [7]:
x=np.array([[1,2,3],[4,5,6]])

In [8]:
type(x)

numpy.ndarray

In [9]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x[0][0]

1

In [11]:
x[0]

array([1, 2, 3])

In [15]:
z=np.random.rand(10)

In [16]:
z

array([0.52744889, 0.50178083, 0.21182726, 0.74760213, 0.31149707,
       0.91510225, 0.99578222, 0.64966391, 0.60560343, 0.52127154])

In [21]:
b=np.arange(1,10)

In [22]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
len(b)

9

In [26]:
b[:4]

array([1, 2, 3, 4])

In [28]:
arr=np.random.rand(30)

In [29]:
arr

array([0.98838617, 0.30653771, 0.13580782, 0.1236776 , 0.86445521,
       0.04699167, 0.98242231, 0.36901559, 0.09370048, 0.82578715,
       0.59911607, 0.49303395, 0.93137859, 0.62568985, 0.89839095,
       0.06799661, 0.26358428, 0.9526056 , 0.73094547, 0.86899874,
       0.22770892, 0.04080735, 0.64503519, 0.18597979, 0.8185734 ,
       0.54771466, 0.42346767, 0.24115733, 0.60272363, 0.35465883])

In [40]:
z=arr.reshape(5,6)

In [42]:
z[0:2,3:5]

array([[0.1236776 , 0.86445521],
       [0.82578715, 0.59911607]])

In [62]:
np.random.seed(12)

In [63]:
np.random.randint(1,100)

76

In [72]:
np.linspace(1,2,4)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [74]:
arr.max()

0.9883861670548343

In [ ]:
d